# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
 dockerRegistryServiceConnection: 'eb0a6819-ff89-46c8-8569-d864ff13a959'
  imgRepo: 'prova'
  containerRegistry: 'kuberegistry2023.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'

   vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: fedePool
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build to registry
      inputs:
        command: buildAndPush
        containerRegistry: 'kuberegistry2023.azurecr.io'
        repository: '$(imgRepo)'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(tag)'
